### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by erlend-sh** [commune-os/commune-server#1]
Short-term roadmap
- [ ] Federation between Commune instances
- [ ] Social login support
- [ ] ActivityPub support for interacting with the fediverse
- [ ] Private spaces/boards and Encrypted DMs
- [ ] Simplify self-hosting deployment
- [ ] Discord bridge
